version: "3"
services:
  db:
    env_file:
      - .env
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB:-db123}"
      POSTGRES_HOST: "${POSTGRES_HOST:-db}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    env_file:
      - .env
    image: galethegreat/rcubot:latest
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - db
    volumes:
      - F:/Code/rucbot/:/usr/src/app

volumes:
  db-data:
