name: Publish rcubot Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  
  build_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci 
      - name: test
        run: npm run test
  push_to_Docker_Hub:
    runs-on: ubuntu-latest
      # build docker image and push to docker hub
      # only if the app build and test successfully
    needs: [build_test]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
       
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rcubot:latest
        
    
    

